# Desc: opaque plugin makefile
# CVS: $Id$

all: libopaquedriver.so

%.o: %.cc
	$(CXX) -Wall -fpic -g3 `pkg-config --cflags playercore` -c $<

libopaquedriver.so: opaquedriver.o
	$(CXX) -shared -nostartfiles -o $@ $^

clean:
	rm -f *.o *.so
